"""Supported cross-feature API for prospect intelligence."""

from .contracts import (
    PROSPECT_FILES,
    Account,
    AccountRelationship,
    AnalysisOutput,
    ArtifactManifestEntry,
    ArtifactMediaType,
    Evidence,
    FitVerdict,
    LaneAnalysisArtifact,
    LaneFitResult,
    NetworkLane,
    OutreachDraft,
    ProspectBrief,
    ProspectFileContract,
    ProspectRun,
    Provenance,
    QualityEvent,
    QualityEventType,
    RecommendedNextStep,
    ReviewAction,
    RunError,
    RunStatus,
    ScoredLane,
    ShipperLane,
    SourceCoverage,
    SourceCoverageStatus,
    SourceMode,
)
from .domain.lane_fit import rank_lane_fits
from .fixtures.synthetic import (
    SYNTHETIC_DATASET_SEED,
    SYNTHETIC_DATASET_VERSION,
    ScenarioInputPayload,
    SyntheticScenario,
    canonical_scenarios_bytes,
    generate_synthetic_scenarios,
    scenario_payload,
)
from .integrations.market_data import (
    FafSnapshotManifest,
    load_faf_snapshot_manifest,
    verify_faf_snapshot,
)

__all__ = [
    "PROSPECT_FILES",
    "SYNTHETIC_DATASET_SEED",
    "SYNTHETIC_DATASET_VERSION",
    "Account",
    "AccountRelationship",
    "AnalysisOutput",
    "ArtifactManifestEntry",
    "ArtifactMediaType",
    "Evidence",
    "FafSnapshotManifest",
    "FitVerdict",
    "LaneAnalysisArtifact",
    "LaneFitResult",
    "NetworkLane",
    "OutreachDraft",
    "ProspectBrief",
    "ProspectFileContract",
    "ProspectRun",
    "Provenance",
    "QualityEvent",
    "QualityEventType",
    "RecommendedNextStep",
    "ReviewAction",
    "RunError",
    "RunStatus",
    "ScenarioInputPayload",
    "ScoredLane",
    "ShipperLane",
    "SourceCoverage",
    "SourceCoverageStatus",
    "SourceMode",
    "SyntheticScenario",
    "canonical_scenarios_bytes",
    "generate_synthetic_scenarios",
    "load_faf_snapshot_manifest",
    "rank_lane_fits",
    "scenario_payload",
    "verify_faf_snapshot",
]
